### ISSUE TITLE
"Current file path not set!" ScoverageException being thrown

### ISSUE THREAD

**Issue by SinghAsDev** [RadoBuransky/sonar-scoverage-plugin#10]
I am using sonar-scoverage-plugin-1.1.0 with gradle-scoverage:1.0-5-g9c68988 and SonarQube 4.2.

Below is the ST:
```
16:27:06.278 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: com.buransky.plugins.scoverage.ScoverageException: Current file path not set!
16:27:06.278 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.buransky.plugins.scoverage.xml.XmlScoverageReportConstructingParser.elemStart(XmlScoverageReportConstructingParser.scala:80)
16:27:06.278 [ERROR] [org.gradle.BuildExceptionReporter] 	at scala.xml.parsing.MarkupParser$class.element1(MarkupParser.scala:566)
16:27:06.278 [ERROR] [org.gradle.BuildExceptionReporter] 	at scala.xml.parsing.ConstructingParser.element1(ConstructingParser.scala:47)
16:27:06.279 [ERROR] [org.gradle.BuildExceptionReporter] 	at scala.xml.parsing.MarkupParser$class.content1(MarkupParser.scala:418)
16:27:06.279 [ERROR] [org.gradle.BuildExceptionReporter] 	at scala.xml.parsing.ConstructingParser.content1(ConstructingParser.scala:47)
16:27:06.279 [ERROR] [org.gradle.BuildExceptionReporter] 	at scala.xml.parsing.MarkupParser$class.content(MarkupParser.scala:442)
16:27:06.279 [ERROR] [org.gradle.BuildExceptionReporter] 	at scala.xml.parsing.ConstructingParser.content(ConstructingParser.scala:47)
16:27:06.280 [ERROR] [org.gradle.BuildExceptionReporter] 	at scala.xml.parsing.MarkupParser$class.element1(MarkupParser.scala:567)
16:27:06.280 [ERROR] [org.gradle.BuildExceptionReporter] 	at scala.xml.parsing.ConstructingParser.element1(ConstructingParser.scala:47)
16:27:06.280 [ERROR] [org.gradle.BuildExceptionReporter] 	at scala.xml.parsing.MarkupParser$class.content1(MarkupParser.scala:418)
16:27:06.280 [ERROR] [org.gradle.BuildExceptionReporter] 	at scala.xml.parsing.ConstructingParser.content1(ConstructingParser.scala:47)
16:27:06.281 [ERROR] [org.gradle.BuildExceptionReporter] 	at scala.xml.parsing.MarkupParser$class.document(MarkupParser.scala:239)
16:27:06.281 [ERROR] [org.gradle.BuildExceptionReporter] 	at scala.xml.parsing.ConstructingParser.document(ConstructingParser.scala:47)
16:27:06.281 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.buransky.plugins.scoverage.xml.XmlScoverageReportConstructingParser.parse(XmlScoverageReportConstructingParser.scala:55)
16:27:06.281 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.buransky.plugins.scoverage.xml.XmlScoverageReportParser.parse(XmlScoverageReportParser.scala:42)
16:27:06.282 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.buransky.plugins.scoverage.sensor.ScoverageSensor.analyse(ScoverageSensor.scala:55)
16:27:06.282 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.sonar.batch.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:79)
16:27:06.282 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.sonar.batch.phases.SensorsExecutor.execute(SensorsExecutor.java:70)
16:27:06.282 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.sonar.batch.phases.PhaseExecutor.execute(PhaseExecutor.java:134)
16:27:06.283 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.sonar.batch.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:186)
16:27:06.283 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.sonar.api.platform.ComponentContainer.startComponents(ComponentContainer.java:92)
16:27:06.283 [ERROR] [org.gradle.BuildExceptionReporter] 	... 99 more

```

**Comment by RadoBuransky** [comment]
I have a feeling that the issue is related to the Gradle Scoverage plugin. Can you send me the coverage XML report? Perhaps please try to use the latest version 1.0.6: https://github.com/scoverage/gradle-scoverage/releases/tag/1.0.6
