### ISSUE TITLE
ScoverageSensor could not find settings key

### ISSUE THREAD

**Issue by vromancas** [RadoBuransky/sonar-scoverage-plugin#30]
Hi,

I updated to Sonarqube 5.3 and Scoverage-Sbt Plugin 1.3.5 and I keep getting the following error:

C:\tv\sonar-runner-2.4\bin\..
SonarQube Runner 2.4
Java 1.8.0_66 Oracle Corporation (64-bit)
Windows 10 10.0 amd64
INFO: Error stacktraces are turned on.
INFO: Runner configuration file: C:\tv\sonar-runner-2.4\bin\..\conf\sonar-runner.properties
INFO: Project configuration file: C:\Users\Public\Documents\Repos\entrypoints-vroman-dev\sonar-project.properties
INFO: Default locale: "en_US", source code encoding: "UTF-8"
INFO: Work directory: C:\Users\Public\Documents\Repos\entrypoints-vroman-dev\.\.sonar
INFO: SonarQube Server 5.3
14:29:54.165 DEBUG - Publish global mode
14:29:54.238 DEBUG - cache: C:\Users\Default.BOSlVRoman\.sonar\ws_cache\http%3A%2F%2Flocalhost%3A9999\global
14:29:54.279 INFO  - Load global repositories
14:29:54.567 DEBUG - GET 200 http://localhost:9999/batch/global | time=284ms
14:29:54.635 INFO  - Load global repositories (done) | time=357ms
14:29:54.655 INFO  - User cache: C:\Users\Default.BOSlVRoman\.sonar\cache
14:29:54.890 INFO  - Load plugins index
14:29:54.896 DEBUG - GET 200 http://localhost:9999/deploy/plugins/index.txt | time=6ms
14:29:54.898 INFO  - Load plugins index (done) | time=8ms
14:29:54.899 DEBUG - Load plugins
14:29:54.909 DEBUG - Load plugins (done) | time=10ms
14:29:54.916 DEBUG - API compatibility mode is enabled on plugin Scoverage [scoverage] (built with API lower than 5.2)
14:29:55.006 DEBUG - Plugins:
14:29:55.007 DEBUG -   * Scoverage 5.1.2 (scoverage)
14:29:55.326 INFO  - Process project properties
14:29:55.328 DEBUG - Process project properties (done) | time=2ms
14:29:55.368 DEBUG - cache: C:\Users\Default.BOSlVRoman\.sonar\ws_cache\http%3A%2F%2Flocalhost%3A9999\5.3\projects\org.tiekinetix.us.CSP-EntryPoints
14:29:55.369 INFO  - Load project repositories
14:29:55.480 DEBUG - GET 200 http://localhost:9999/batch/project.protobuf?key=org.tiekinetix.us.CSP-EntryPoints | time=111ms
14:29:55.579 INFO  - Load project repositories (done) | time=210ms
14:29:55.587 INFO  - Apply project exclusions
14:29:55.643 DEBUG - Available languages:
14:29:55.644 DEBUG -   * Scala => "scala"
14:29:55.647 INFO  - Load quality profiles
14:29:55.719 DEBUG - GET 200 http://localhost:9999/api/qualityprofiles/search.protobuf?projectKey=org.tiekinetix.us.CSP-EntryPoints | time=72ms
14:29:55.731 INFO  - Load quality profiles (done) | time=84ms
14:29:55.734 INFO  - Load active rules
14:29:55.799 DEBUG - GET 200 http://localhost:9999/api/rules/search.protobuf?f=repo,name,severity,lang,internalKey,templateKey,params,actives&activation=true&qprofile=scala-scala-quality-profile-12683&p=1&ps=500 | time=65ms
14:29:55.818 INFO  - Load active rules (done) | time=84ms
14:29:55.827 WARN  - SCM provider autodetection failed. No SCM provider claims to support this project. Please use sonar.scm.provider to define SCM of your project.
14:29:55.828 INFO  - Publish mode
14:29:55.828 DEBUG - Start recursive analysis of project modules
14:29:55.829 INFO  - -------------  Scan CSP-EntryPoints
14:29:55.889 INFO  - Load server rules
14:29:55.914 DEBUG - GET 200 http://localhost:9999/api/rules/list.protobuf | time=25ms
14:29:55.926 INFO  - Load server rules (done) | time=37ms
14:29:55.959 DEBUG - Initializers : 
14:29:55.960 INFO  - Base dir: C:\Users\Public\Documents\Repos\entrypoints-vroman-dev
14:29:55.960 INFO  - Working dir: C:\Users\Public\Documents\Repos\entrypoints-vroman-dev\.sonar
14:29:55.961 INFO  - Source paths: app
14:29:55.961 INFO  - Source encoding: UTF-8, default locale: en_US
14:29:55.962 INFO  - Index files
14:29:55.963 DEBUG - Declared extensions of language Scala were converted to sonar.lang.patterns.scala : **/*.scala
14:29:55.970 DEBUG - Language of file 'app/controllers/AssetSyndication.scala' is detected to be 'scala'
14:29:55.970 DEBUG - Language of file 'app/controllers/Campaign.scala' is detected to be 'scala'
14:29:55.971 DEBUG - Language of file 'app/controllers/Download.scala' is detected to be 'scala'
14:29:55.971 DEBUG - Language of file 'app/controllers/Inline.scala' is detected to be 'scala'
14:29:55.971 DEBUG - Language of file 'app/controllers/MainRoutingTable.scala' is detected to be 'scala'
14:29:55.972 DEBUG - Language of file 'app/controllers/PartnerLocator.scala' is detected to be 'scala'
14:29:55.972 DEBUG - Language of file 'app/controllers/SalesResourceCenter.scala' is detected to be 'scala'
14:29:55.985 DEBUG - Language of file 'app/controllers/TestUI.scala' is detected to be 'scala'
14:29:55.985 DEBUG - Language of file 'app/controllers/ShowcaseEP.scala' is detected to be 'scala'
14:29:55.985 DEBUG - Language of file 'app/controllers/VideoPlayer.scala' is detected to be 'scala'
14:29:55.985 DEBUG - Language of file 'app/Global.scala' is detected to be 'scala'
14:29:55.985 DEBUG - Language of file 'app/models/business/APIErrorResponseHandler.scala' is detected to be 'scala'
14:29:55.986 DEBUG - Language of file 'app/models/business/AssetSyndicationCustomerOptions.scala' is detected to be 'scala'
14:29:55.986 DEBUG - Language of file 'app/models/business/AssetSyndicationValidator.scala' is detected to be 'scala'
14:29:55.987 DEBUG - Language of file 'app/models/business/CampaignCustomerOptions.scala' is detected to be 'scala'
14:29:55.987 DEBUG - Language of file 'app/models/business/CampaignValidator.scala' is detected to be 'scala'
14:29:55.987 DEBUG - Language of file 'app/models/business/CompanyInformation.scala' is detected to be 'scala'
14:29:55.987 DEBUG - Language of file 'app/models/business/CustomerOptions.scala' is detected to be 'scala'
14:29:55.989 DEBUG - Language of file 'app/models/business/InlineCustomerOptions.scala' is detected to be 'scala'
14:29:55.989 DEBUG - Language of file 'app/models/business/InlineValidator.scala' is detected to be 'scala'
14:29:55.990 DEBUG - Language of file 'app/models/business/PartnerLocatorCustomerOptions.scala' is detected to be 'scala'
14:29:55.991 DEBUG - Language of file 'app/models/business/PartnerLocatorValidator.scala' is detected to be 'scala'
14:29:55.992 DEBUG - Language of file 'app/models/business/SalesRCCustomerOptions.scala' is detected to be 'scala'
14:29:55.992 DEBUG - Language of file 'app/models/business/SalesResourceCenterValidator.scala' is detected to be 'scala'
14:29:55.994 DEBUG - Language of file 'app/models/business/ShowcaseCustomerOptions.scala' is detected to be 'scala'
14:29:55.995 DEBUG - Language of file 'app/models/core/AssambleResponse.scala' is detected to be 'scala'
14:29:55.996 DEBUG - Language of file 'app/models/business/ShowcaseValidator.scala' is detected to be 'scala'
14:29:55.998 DEBUG - Language of file 'app/models/core/InlineSyndicationAssembler.scala' is detected to be 'scala'
14:29:55.999 DEBUG - Language of file 'app/models/core/ResponseLogicByLaunchType.scala' is detected to be 'scala'
14:29:55.999 DEBUG - Language of file 'app/models/core/UIEntryPoint.scala' is detected to be 'scala'
14:29:56.000 DEBUG - Language of file 'app/models/core/UIGetDependencies.scala' is detected to be 'scala'
14:29:56.000 DEBUG - Language of file 'app/models/reports/NewRelicBrowserHandlers.scala' is detected to be 'scala'
14:29:56.002 DEBUG - Language of file 'app/models/reports/UIWebTrends.scala' is detected to be 'scala'
14:29:56.002 DEBUG - Language of file 'app/models/utilities/BrowserCheck.scala' is detected to be 'scala'
14:29:56.002 DEBUG - Language of file 'app/models/utilities/LoadUIFiles.scala' is detected to be 'scala'
14:29:56.003 DEBUG - Language of file 'app/models/utilities/Patches.scala' is detected to be 'scala'
14:29:56.004 DEBUG - Language of file 'app/models/utilities/POCSampler.scala' is detected to be 'scala'
14:29:56.005 DEBUG - Language of file 'app/models/utilities/UniqueID.scala' is detected to be 'scala'
14:29:56.006 DEBUG - Language of file 'app/models/utilities/VideoSolver.scala' is detected to be 'scala'
14:29:56.017 INFO  - 39 files indexed
14:29:56.023 INFO  - Quality profile for scala: Scala Quality Profile
14:29:56.027 DEBUG - Code colorizer, supported languages: 
14:29:56.032 DEBUG - Sensors : Lines Sensor (wrapped) -> QProfileSensor -> ScoverageSensor -> SCM Sensor (wrapped) -> Code Colorizer Sensor (wrapped) -> CPD Sensor (wrapped)
14:29:56.033 INFO  - Sensor Lines Sensor (wrapped)
14:29:56.048 INFO  - Sensor Lines Sensor (wrapped) (done) | time=15ms
14:29:56.048 INFO  - Sensor QProfileSensor
14:29:56.051 INFO  - Sensor QProfileSensor (done) | time=3ms
14:29:56.051 INFO  - Sensor ScoverageSensor
14:29:56.057 WARN  - could not find settings key CSP-EntryPoints.sonar.sources assuming src/main/scala.
14:29:56.058 INFO  - Analysis report generated in C:\Users\Public\Documents\Repos\entrypoints-vroman-dev\.\.sonar\batch-report
INFO: ------------------------------------------------------------------------
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
Total time: 7.793s
Final Memory: 8M/159M
INFO: ------------------------------------------------------------------------
ERROR: Error during Sonar runner execution
org.sonar.runner.impl.RunnerException: Unable to execute Sonar
        at org.sonar.runner.impl.BatchLauncher$1.delegateExecution(BatchLauncher.java:91)
        at org.sonar.runner.impl.BatchLauncher$1.run(BatchLauncher.java:75)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.sonar.runner.impl.BatchLauncher.doExecute(BatchLauncher.java:69)
        at org.sonar.runner.impl.BatchLauncher.execute(BatchLauncher.java:50)
        at org.sonar.runner.api.EmbeddedRunner.doExecute(EmbeddedRunner.java:102)
        at org.sonar.runner.api.Runner.execute(Runner.java:100)
        at org.sonar.runner.Main.executeTask(Main.java:70)
        at org.sonar.runner.Main.execute(Main.java:59)
        at org.sonar.runner.Main.main(Main.java:53)
Caused by: java.lang.IllegalArgumentException: requirement failed
        at scala.Predef$.require(Predef.scala:207)
        at com.buransky.plugins.scoverage.pathcleaner.BruteForceSequenceMatcher.<init>(BruteForceSequenceMatcher.scala:54)
        at com.buransky.plugins.scoverage.sensor.ScoverageSensor.createPathSanitizer(ScoverageSensor.scala:78)
        at com.buransky.plugins.scoverage.sensor.ScoverageSensor.analyse(ScoverageSensor.scala:66)
        at org.sonar.batch.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:58)
        at org.sonar.batch.phases.SensorsExecutor.execute(SensorsExecutor.java:50)
        at org.sonar.batch.phases.PhaseExecutor.execute(PhaseExecutor.java:98)
        at org.sonar.batch.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:185)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:132)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:117)
        at org.sonar.batch.scan.ProjectScanContainer.scan(ProjectScanContainer.java:243)
        at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:238)
        at org.sonar.batch.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:228)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:132)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:117)
        at org.sonar.batch.task.ScanTask.execute(ScanTask.java:55)
        at org.sonar.batch.task.TaskContainer.doAfterStart(TaskContainer.java:86)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:132)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:117)
        at org.sonar.batch.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:122)
        at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:119)
        at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:79)
        at org.sonar.runner.batch.IsolatedLauncher.execute(IsolatedLauncher.java:48)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.sonar.runner.impl.BatchLauncher$1.delegateExecution(BatchLauncher.java:87)
        ... 9 more

Thank you for your help
Victor

**Comment by tg44** [comment]
I have this too... Sonar 5.2.

**Comment by tomdevroomen** [comment]
I have this too on Sonar 5.4, I downloaded the source and updatd the ScoverageSensor to search for setting sonar.sources. Just like to have to do in the sonar-project.properties files in your project.

For me this works... Still testing things.

@RadoBuransky What was the reason to include the project name with this setting?

**Comment by Krever** [comment]
For me the problem was with multiple(comma-separated) paths passed to `sonar.sources` which is allowed by sonar docs. Should I rise separate issue for this problem?

**Comment by politrons** [comment]
Any update of this problem?
