### ISSUE TITLE
Unable to run Sonar-Scanner 2.6 with SonarQube 5.6LTS

### ISSUE THREAD

**Issue by farhansumbul** [RadoBuransky/sonar-scoverage-plugin#36]
Hello Everyone, 

I am facing below error whenever I try to analyse few codes. Here is the error log:

C:\sonar-scanner-2.6.1\projects>C:\sonar-scanner-2.6.1\bin\sonar-scanner.bat -X
C:\sonar-scanner-2.6.1\bin\..
INFO: Scanner configuration file: C:\sonar-scanner-2.6.1\bin\..\conf\sonar-scanner.properties
INFO: Project root configuration file: C:\sonar-scanner-2.6.1\projects\sonar-project.properties
INFO: SonarQube Scanner 2.6.1
INFO: Java 1.8.0_101 Oracle Corporation (64-bit)
INFO: Windows 10 10.0 amd64
INFO: User cache: C:\Users\farhans\.sonar\cache
DEBUG: Extract sonar-scanner-api-batch in temp...
DEBUG: Get bootstrap index...
DEBUG: Download: http://localhost:9000/batch_bootstrap/index
DEBUG: Get bootstrap completed
DEBUG: Create isolated classloader...
DEBUG: Start temp cleaning...
DEBUG: Temp cleaning done
DEBUG: Execution getVersion
DEBUG: Execution start
DEBUG: Publish global mode
INFO: Load global repositories
DEBUG: GET 200 http://localhost:9000/batch/global | time=141ms
INFO: Load global repositories (done) | time=250ms
INFO: User cache: C:\Users\farhans\.sonar\cache
INFO: Load plugins index
DEBUG: GET 200 http://localhost:9000/deploy/plugins/index.txt | time=15ms
INFO: Load plugins index (done) | time=15ms
DEBUG: Load plugins
DEBUG: Load plugins (done) | time=16ms
DEBUG: API compatibility mode is enabled on plugin Web [web] (built with API lower than 5.2)
DEBUG: API compatibility mode is enabled on plugin XML [xml] (built with API lower than 5.2)
DEBUG: API compatibility mode is enabled on plugin PHP [php] (built with API lower than 5.2)
DEBUG: API compatibility mode is enabled on plugin JSON [JSON] (built with API lower than 5.2)
DEBUG: Plugins:
DEBUG:   * Java Properties 2.0 (javaProperties)
DEBUG:   * CSS 2.0 (css)
DEBUG:   * Java Properties 2.1.1 (jproperties)
DEBUG:   * Java 4.1 (java)
DEBUG:   * Web 2.4 (web)
DEBUG:   * XML 1.4.1 (xml)
DEBUG:   * Bitbucket Authentication for SonarQube 1.0 (authbitbucket)
DEBUG:   * PHP 2.8 (php)
DEBUG:   * JSON 1.4 (JSON)
DEBUG:   * JavaScript 2.15 (javascript)
DEBUG: Execution getVersion
INFO: SonarQube server 5.6
INFO: Default locale: "en_IN", source code encoding: "UTF-8"
DEBUG: Work directory: C:\sonar-scanner-2.6.1\projects\.sonar
DEBUG: Execution getVersion
DEBUG: Execution execute
INFO: Process project properties
DEBUG: Process project properties (done) | time=16ms
INFO: Load project repositories
DEBUG: GET 404 http://localhost:9000/batch/project.protobuf?key=SampleProject | time=31ms
DEBUG: Project repository not available - continuing without it
org.sonarqube.ws.client.HttpException: Error 404 on http://localhost:9000/batch/project.protobuf?key=SampleProject
        at org.sonarqube.ws.client.BaseResponse.failIfNotSuccessful(BaseResponse.java:34) ~[sonar-scanner-engine-shaded-5.6.jar:na]
        at org.sonar.batch.bootstrap.BatchWsClient.failIfUnauthorized(BatchWsClient.java:99) ~[sonar-scanner-engine-shaded-5.6.jar:na]
        at org.sonar.batch.bootstrap.BatchWsClient.call(BatchWsClient.java:69) ~[sonar-scanner-engine-shaded-5.6.jar:na]
        at org.sonar.batch.repository.DefaultProjectRepositoriesLoader.load(DefaultProjectRepositoriesLoader.java:58) ~[sonar-scanner-engine-shaded-5.6.jar:na]
        at org.sonar.batch.repository.ProjectRepositoriesProvider.provide(ProjectRepositoriesProvider.java:39) [sonar-scanner-engine-shaded-5.6.jar:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_101]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_101]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_101]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_101]
        at org.picocontainer.injectors.MethodInjector.invokeMethod(MethodInjector.java:129) [sonar-scanner-engine-shaded-5.6.jar:na]
        at org.picocontainer.injectors.MethodInjector.access$000(MethodInjector.java:39) [sonar-scanner-engine-shaded-5.6.jar:na]
        at org.picocontainer.injectors.MethodInjector$2.run(MethodInjector.java:113) [sonar-scanner-engine-shaded-5.6.jar:na]
        at org.picocontainer.injectors.AbstractInjector$ThreadLocalCyclicDependencyGuard.observe(AbstractInjector.java:270) [sonar-scanner-engine-shaded-5.6.jar:na]
        at org.picocontainer.injectors.MethodInjector.decorateComponentInstance(MethodInjector.java:120) [sonar-scanner-engine-shaded-5.6.jar:na]
        at org.picocontainer.injectors.CompositeInjector.decorateComponentInstance(CompositeInjector.java:58) [sonar-scanner-engine-shaded-5.6.jar:na]
        at org.picocontainer.injectors.Reinjector.reinject(Reinjector.java:142) [sonar-scanner-engine-shaded-5.6.jar:na]
        at org.picocontainer.injectors.ProviderAdapter.getComponentInstance(ProviderAdapter.java:96) [sonar-scanner-engine-shaded-5.6.jar:na]
        at org.picocontainer.DefaultPicoContainer.getInstance(DefaultPicoContainer.java:699) [sonar-scanner-engine-shaded-5.6.jar:na]
        at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:647) [sonar-scanner-engine-shaded-5.6.jar:na]
        at org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer.getComponent(ComponentContainer.java:67) [sonar-scanner-engine-shaded-5.6.jar:na]
        at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:632) [sonar-scanner-engine-shaded-5.6.jar:na]
        at org.picocontainer.parameters.BasicComponentParameter$1.resolveInstance(BasicComponentParameter.java:118) [sonar-scanner-engine-shaded-5.6.jar:na]
        at org.picocontainer.parameters.ComponentParameter$1.resolveInstance(ComponentParameter.java:136) [sonar-scanner-engine-shaded-5.6.jar:na]
        at org.picocontainer.injectors.SingleMemberInjector.getParameter(SingleMemberInjector.java:78) [sonar-scanner-engine-shaded-5.6.jar:na]
        at org.picocontainer.injectors.ConstructorInjector$CtorAndAdapters.getParameterArguments(ConstructorInjector.java:309) [sonar-scanner-engine-shaded-5.6.jar:na]
        at org.picocontainer.injectors.ConstructorInjector$1.run(ConstructorInjector.java:335) [sonar-scanner-engine-shaded-5.6.jar:na]
        at org.picocontainer.injectors.AbstractInjector$ThreadLocalCyclicDependencyGuard.observe(AbstractInjector.java:270) [sonar-scanner-engine-shaded-5.6.jar:na]
        at org.picocontainer.injectors.ConstructorInjector.getComponentInstance(ConstructorInjector.java:364) [sonar-scanner-engine-shaded-5.6.jar:na]
        at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.getComponentInstance(AbstractInjectionFactory.java:56) [sonar-scanner-engine-shaded-5.6.jar:na]
        at org.picocontainer.behaviors.AbstractBehavior.getComponentInstance(AbstractBehavior.java:64) [sonar-scanner-engine-shaded-5.6.jar:na]
        at org.picocontainer.behaviors.Stored.getComponentInstance(Stored.java:91) [sonar-scanner-engine-shaded-5.6.jar:na]
        at org.picocontainer.DefaultPicoContainer.getInstance(DefaultPicoContainer.java:699) [sonar-scanner-engine-shaded-5.6.jar:na]
        at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:647) [sonar-scanner-engine-shaded-5.6.jar:na]
        at org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer.getComponent(ComponentContainer.java:67) [sonar-scanner-engine-shaded-5.6.jar:na]
        at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:678) [sonar-scanner-engine-shaded-5.6.jar:na]
        at org.sonar.core.platform.ComponentContainer.getComponentByType(ComponentContainer.java:272) [sonar-scanner-engine-shaded-5.6.jar:na]
        at org.sonar.batch.scan.ProjectScanContainer.doBeforeStart(ProjectScanContainer.java:112) [sonar-scanner-engine-shaded-5.6.jar:na]
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:140) [sonar-scanner-engine-shaded-5.6.jar:na]
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127) [sonar-scanner-engine-shaded-5.6.jar:na]
        at org.sonar.batch.task.ScanTask.execute(ScanTask.java:47) [sonar-scanner-engine-shaded-5.6.jar:na]
        at org.sonar.batch.task.TaskContainer.doAfterStart(TaskContainer.java:86) [sonar-scanner-engine-shaded-5.6.jar:na]
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142) [sonar-scanner-engine-shaded-5.6.jar:na]
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127) [sonar-scanner-engine-shaded-5.6.jar:na]
        at org.sonar.batch.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:106) [sonar-scanner-engine-shaded-5.6.jar:na]
        at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:119) [sonar-scanner-engine-shaded-5.6.jar:na]
        at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:62) [sonar-scanner-api-batch6025374883761456175.jar:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_101]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_101]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_101]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_101]
        at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60) [sonar-scanner-cli-2.6.1.jar:na]
        at com.sun.proxy.$Proxy0.execute(Unknown Source) [na:na]
        at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:240) [sonar-scanner-cli-2.6.1.jar:na]
        at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151) [sonar-scanner-cli-2.6.1.jar:na]
        at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:110) [sonar-scanner-cli-2.6.1.jar:na]
        at org.sonarsource.scanner.cli.Main.execute(Main.java:72) [sonar-scanner-cli-2.6.1.jar:na]
        at org.sonarsource.scanner.cli.Main.main(Main.java:60) [sonar-scanner-cli-2.6.1.jar:na]

INFO: Load project repositories (done) | time=219ms
DEBUG: Available languages:
DEBUG:   * Java Properties => "jproperties"
DEBUG:   * CSS => "css"
DEBUG:   * Java Properties => "jproperties"
DEBUG:   * Java => "java"
DEBUG:   * Web => "web"
DEBUG:   * XML => "xml"
DEBUG:   * PHP => "php"
DEBUG:   * JSON => "json"
DEBUG:   * JavaScript => "js"
INFO: Load quality profiles
DEBUG: GET 200 http://localhost:9000/api/qualityprofiles/search.protobuf?defaults=true | time=94ms
INFO: Load quality profiles (done) | time=109ms
INFO: Load active rules
DEBUG: GET 200 http://localhost:9000/api/rules/search.protobuf?f=repo,name,severity,lang,internalKey,templateKey,params,actives&activation=true&qprofile=css-sonarqube-way-23980&p=1&ps=500 | time=203ms
DEBUG: GET 200 http://localhost:9000/api/rules/search.protobuf?f=repo,name,severity,lang,internalKey,templateKey,params,actives&activation=true&qprofile=java-sonar-way-98502&p=1&ps=500 | time=438ms
DEBUG: GET 200 http://localhost:9000/api/rules/search.protobuf?f=repo,name,severity,lang,internalKey,templateKey,params,actives&activation=true&qprofile=jproperties-sonarqube-way-04165&p=1&ps=500 | time=313ms
DEBUG: GET 200 http://localhost:9000/api/rules/search.protobuf?f=repo,name,severity,lang,internalKey,templateKey,params,actives&activation=true&qprofile=js-sonar-way-76980&p=1&ps=500 | time=125ms
DEBUG: GET 200 http://localhost:9000/api/rules/search.protobuf?f=repo,name,severity,lang,internalKey,templateKey,params,actives&activation=true&qprofile=json-sonarqube-way-52063&p=1&ps=500 | time=234ms
DEBUG: GET 200 http://localhost:9000/api/rules/search.protobuf?f=repo,name,severity,lang,internalKey,templateKey,params,actives&activation=true&qprofile=php-sonar-way-84069&p=1&ps=500 | time=78ms
DEBUG: GET 200 http://localhost:9000/api/rules/search.protobuf?f=repo,name,severity,lang,internalKey,templateKey,params,actives&activation=true&qprofile=web-sonar-way-92743&p=1&ps=500 | time=31ms
DEBUG: GET 200 http://localhost:9000/api/rules/search.protobuf?f=repo,name,severity,lang,internalKey,templateKey,params,actives&activation=true&qprofile=xml-sonar-way-69142&p=1&ps=500 | time=94ms
INFO: Load active rules (done) | time=1781ms
DEBUG: SCM Step is disabled by configuration
INFO: Publish mode
DEBUG: Start recursive analysis of project modules
INFO: -------------  Scan Module1
INFO: Load server rules
DEBUG: GET 200 http://localhost:9000/api/rules/list.protobuf | time=78ms
INFO: Load server rules (done) | time=125ms
DEBUG: Initializers :
INFO: Base dir: C:\sonar-scanner-2.6.1\projects\module1
INFO: Working dir: C:\sonar-scanner-2.6.1\projects\.sonar\SampleProject_module1
INFO: Source paths: src
INFO: Source encoding: UTF-8, default locale: en_IN
INFO: Index files
DEBUG: Declared extensions of language Java Properties were converted to sonar.lang.patterns.jproperties : **/*.properties
DEBUG: Declared extensions of language CSS were converted to sonar.lang.patterns.css : **/*.css
DEBUG: Declared extensions of language Java were converted to sonar.lang.patterns.java : **/*.java,**/*.jav
DEBUG: Declared extensions of language Web were converted to sonar.lang.patterns.web : **/*.html,**/*.xhtml,**/*.rhtml,**/*.shtml
DEBUG: Declared extensions of language XML were converted to sonar.lang.patterns.xml : **/*.xml
DEBUG: Declared extensions of language PHP were converted to sonar.lang.patterns.php : **/*.php,**/*.php3,**/*.php4,**/*.php5,**/*.phtml,**/*.inc
DEBUG: Declared extensions of language JSON were converted to sonar.lang.patterns.json : **/*.json
DEBUG: Declared extensions of language JavaScript were converted to sonar.lang.patterns.js : **/*.js
DEBUG: Language of file 'src/forgot_password.html' is detected to be 'web'
DEBUG: Language of file 'src/login_form.html' is detected to be 'web'
DEBUG: Language of file 'src/reset_password.html' is detected to be 'web'
INFO: 3 files indexed
INFO: Quality profile for web: Sonar way
DEBUG: Code colorizer, supported languages: web
DEBUG: 'Java Properties Squid Sensor' skipped because there is no related file in current project
DEBUG: 'CSS Squid Sensor' skipped because there is no related file in current project
DEBUG: 'Java Properties Squid Sensor' skipped because there is no related file in current project
DEBUG: 'SurefireSensor' skipped because there is no related file in current project
DEBUG: 'JaCoCoSensor' skipped because there is no related file in current project
DEBUG: 'JaCoCoItSensor' skipped because there is no related file in current project
DEBUG: 'JaCoCoOverallSensor' skipped because there is no related file in current project
DEBUG: 'JavaSquidSensor' skipped because there is no related file in current project
DEBUG: 'JavaScript Squid Sensor' skipped because there is no related file in current project
DEBUG: Sensors : Lines Sensor (wrapped) -> WebSensor -> SCM Sensor (wrapped) -> XmlFileSensor (wrapped) -> Zero Coverage Sensor (wrapped) -> Code Colorizer Sensor (wrapped) -> CPD Block Indexer (wrapped)
INFO: Sensor Lines Sensor (wrapped)
INFO: Sensor Lines Sensor (wrapped) (done) | time=16ms
INFO: Sensor WebSensor
DEBUG: WebSensor: src/forgot_password.html:18,0,0,1
DEBUG: Metric lines is an internal metric computed by SonarQube. Provided value is ignored.
DEBUG: WebSensor: src/login_form.html:55,4,0,3
DEBUG: Metric lines is an internal metric computed by SonarQube. Provided value is ignored.
DEBUG: WebSensor: src/reset_password.html:26,0,0,0
DEBUG: Metric lines is an internal metric computed by SonarQube. Provided value is ignored.
INFO: Sensor WebSensor (done) | time=219ms
INFO: Sensor SCM Sensor (wrapped)
INFO: SCM Publisher is disabled
INFO: Sensor SCM Sensor (wrapped) (done) | time=15ms
INFO: Sensor XmlFileSensor (wrapped)
INFO: Sensor XmlFileSensor (wrapped) (done) | time=0ms
INFO: Sensor Zero Coverage Sensor (wrapped)
INFO: Sensor Zero Coverage Sensor (wrapped) (done) | time=47ms
INFO: Sensor Code Colorizer Sensor (wrapped)
INFO: Sensor Code Colorizer Sensor (wrapped) (done) | time=140ms
INFO: Sensor CPD Block Indexer (wrapped)
INFO: DefaultCpdBlockIndexer is used for web
DEBUG: Populating index from C:/sonar-scanner-2.6.1/projects/module1/src/forgot_password.html
DEBUG: Populating index from C:/sonar-scanner-2.6.1/projects/module1/src/login_form.html
DEBUG: Populating index from C:/sonar-scanner-2.6.1/projects/module1/src/reset_password.html
INFO: Sensor CPD Block Indexer (wrapped) (done) | time=63ms
INFO: -------------  Scan Module2
DEBUG: Initializers :
INFO: Base dir: C:\sonar-scanner-2.6.1\projects\module2
INFO: Working dir: C:\sonar-scanner-2.6.1\projects\.sonar\SampleProject_module2
INFO: Source paths: src
INFO: Source encoding: UTF-8, default locale: en_IN
INFO: Index files
DEBUG: Declared extensions of language Java Properties were converted to sonar.lang.patterns.jproperties : **/*.properties
DEBUG: Declared extensions of language CSS were converted to sonar.lang.patterns.css : **/*.css
DEBUG: Declared extensions of language Java were converted to sonar.lang.patterns.java : **/*.java,**/*.jav
DEBUG: Declared extensions of language Web were converted to sonar.lang.patterns.web : **/*.html,**/*.xhtml,**/*.rhtml,**/*.shtml
DEBUG: Declared extensions of language XML were converted to sonar.lang.patterns.xml : **/*.xml
DEBUG: Declared extensions of language PHP were converted to sonar.lang.patterns.php : **/*.php,**/*.php3,**/*.php4,**/*.php5,**/*.phtml,**/*.inc
DEBUG: Declared extensions of language JSON were converted to sonar.lang.patterns.json : **/*.json
DEBUG: Declared extensions of language JavaScript were converted to sonar.lang.patterns.js : **/*.js
DEBUG: Language of file 'src/Person.js' is detected to be 'js'
DEBUG: Language of file 'src/reset_password.html' is detected to be 'web'
INFO: 2 files indexed
INFO: Quality profile for js: Sonar way
INFO: Quality profile for web: Sonar way
DEBUG: 'Java Properties Squid Sensor' skipped because there is no related file in current project
DEBUG: 'CSS Squid Sensor' skipped because there is no related file in current project
DEBUG: 'Java Properties Squid Sensor' skipped because there is no related file in current project
DEBUG: 'SurefireSensor' skipped because there is no related file in current project
DEBUG: 'JaCoCoSensor' skipped because there is no related file in current project
DEBUG: 'JaCoCoItSensor' skipped because there is no related file in current project
DEBUG: 'JaCoCoOverallSensor' skipped because there is no related file in current project
DEBUG: 'JavaSquidSensor' skipped because there is no related file in current project
DEBUG: Sensors : Lines Sensor (wrapped) -> WebSensor -> SCM Sensor (wrapped) -> XmlFileSensor (wrapped) -> JavaScript Squid Sensor (wrapped) -> Zero Coverage Sensor (wrapped) -> Code Colorizer Sensor (wrapped) -> CPD Block Indexer (wrapped)
INFO: Sensor Lines Sensor (wrapped)
INFO: Sensor Lines Sensor (wrapped) (done) | time=0ms
INFO: Sensor WebSensor
DEBUG: WebSensor: src/reset_password.html:26,0,0,0
DEBUG: Metric lines is an internal metric computed by SonarQube. Provided value is ignored.
INFO: Sensor WebSensor (done) | time=31ms
INFO: Sensor SCM Sensor (wrapped)
INFO: SCM Publisher is disabled
INFO: Sensor SCM Sensor (wrapped) (done) | time=0ms
INFO: Sensor XmlFileSensor (wrapped)
INFO: Sensor XmlFileSensor (wrapped) (done) | time=0ms
INFO: Sensor JavaScript Squid Sensor (wrapped)
INFO: 1 source files to be analyzed
INFO: 1/1 source files have been analyzed
INFO: Unit Test Coverage Sensor is started
INFO: Integration Test Coverage Sensor is started
INFO: Overall Coverage Sensor is started
INFO: Sensor JavaScript Squid Sensor (wrapped) (done) | time=532ms
INFO: Sensor Zero Coverage Sensor (wrapped)
INFO: Sensor Zero Coverage Sensor (wrapped) (done) | time=16ms
INFO: Sensor Code Colorizer Sensor (wrapped)
INFO: Sensor Code Colorizer Sensor (wrapped) (done) | time=15ms
INFO: Sensor CPD Block Indexer (wrapped)
INFO: DefaultCpdBlockIndexer is used for js
DEBUG: No CpdMapping for language js
INFO: DefaultCpdBlockIndexer is used for web
DEBUG: Populating index from C:/sonar-scanner-2.6.1/projects/module2/src/reset_password.html
INFO: Sensor CPD Block Indexer (wrapped) (done) | time=16ms
INFO: -------------  Scan SampleProject
DEBUG: Initializers :
INFO: Base dir: C:\sonar-scanner-2.6.1\projects
INFO: Working dir: C:\sonar-scanner-2.6.1\projects\.sonar
INFO: Source encoding: UTF-8, default locale: en_IN
DEBUG: 'Java Properties Squid Sensor' skipped because there is no related file in current project
DEBUG: 'CSS Squid Sensor' skipped because there is no related file in current project
DEBUG: 'Java Properties Squid Sensor' skipped because there is no related file in current project
DEBUG: 'SurefireSensor' skipped because there is no related file in current project
DEBUG: 'JaCoCoSensor' skipped because there is no related file in current project
DEBUG: 'JaCoCoItSensor' skipped because there is no related file in current project
DEBUG: 'JaCoCoOverallSensor' skipped because there is no related file in current project
DEBUG: 'JavaSquidSensor' skipped because there is no related file in current project
DEBUG: 'JavaScript Squid Sensor' skipped because there is no related file in current project
DEBUG: Sensors : Lines Sensor (wrapped) -> SCM Sensor (wrapped) -> XmlFileSensor (wrapped) -> Zero Coverage Sensor (wrapped) -> Code Colorizer Sensor (wrapped) -> CPD Block Indexer (wrapped)
INFO: Sensor Lines Sensor (wrapped)
INFO: Sensor Lines Sensor (wrapped) (done) | time=0ms
INFO: Sensor SCM Sensor (wrapped)
INFO: SCM Publisher is disabled
INFO: Sensor SCM Sensor (wrapped) (done) | time=0ms
INFO: Sensor XmlFileSensor (wrapped)
INFO: Sensor XmlFileSensor (wrapped) (done) | time=0ms
INFO: Sensor Zero Coverage Sensor (wrapped)
INFO: Sensor Zero Coverage Sensor (wrapped) (done) | time=16ms
INFO: Sensor Code Colorizer Sensor (wrapped)
INFO: Sensor Code Colorizer Sensor (wrapped) (done) | time=0ms
INFO: Sensor CPD Block Indexer (wrapped)
INFO: Sensor CPD Block Indexer (wrapped) (done) | time=0ms
INFO: Calculating CPD for 5 files
DEBUG: Detection of duplications for SampleProject:module2:src/Person.js
DEBUG: Detection of duplications for SampleProject:module1:src/forgot_password.html
DEBUG: Detection of duplications for SampleProject:module1:src/reset_password.html
DEBUG: Detection of duplications for SampleProject:module1:src/login_form.html
DEBUG: Detection of duplications for SampleProject:module2:src/reset_password.html
INFO: CPD calculation finished
INFO: Analysis report generated in 266ms, dir size=34 KB
INFO: Analysis reports compressed in 31ms, zip size=18 KB
INFO: Analysis report generated in C:\sonar-scanner-2.6.1\projects\.sonar\batch-report
DEBUG: Upload report
DEBUG: POST 500 http://localhost:9000/api/ce/submit?projectKey=SampleProject&projectName=SampleProject | time=47ms
INFO: ------------------------------------------------------------------------
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
INFO: Total time: 11.000s
INFO: Final Memory: 46M/121M
INFO: ------------------------------------------------------------------------
ERROR: Error during SonarQube Scanner execution
org.sonarqube.ws.client.HttpException: Error 500 on http://localhost:9000/api/ce/submit?projectKey=SampleProject&projectName=SampleProject
        at org.sonarqube.ws.client.BaseResponse.failIfNotSuccessful(BaseResponse.java:34)
        at org.sonar.batch.bootstrap.BatchWsClient.failIfUnauthorized(BatchWsClient.java:99)
        at org.sonar.batch.bootstrap.BatchWsClient.call(BatchWsClient.java:69)
        at org.sonar.batch.report.ReportPublisher.upload(ReportPublisher.java:172)
        at org.sonar.batch.report.ReportPublisher.execute(ReportPublisher.java:127)
        at org.sonar.batch.phases.PublishPhaseExecutor.publishReportJob(PublishPhaseExecutor.java:64)
        at org.sonar.batch.phases.PublishPhaseExecutor.executeOnRoot(PublishPhaseExecutor.java:51)
        at org.sonar.batch.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:86)
        at org.sonar.batch.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:192)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
        at org.sonar.batch.scan.ProjectScanContainer.scan(ProjectScanContainer.java:241)
        at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:236)
        at org.sonar.batch.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:226)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
        at org.sonar.batch.task.ScanTask.execute(ScanTask.java:47)
        at org.sonar.batch.task.TaskContainer.doAfterStart(TaskContainer.java:86)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
        at org.sonar.batch.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:106)
        at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:119)
        at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:62)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
        at com.sun.proxy.$Proxy0.execute(Unknown Source)
        at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:240)
        at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
        at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:110)
        at org.sonarsource.scanner.cli.Main.execute(Main.java:72)
        at org.sonarsource.scanner.cli.Main.main(Main.java:60)

-----------------------------------------------------------------------------------------------

Please advise.

**Comment by xiaoshyang** [comment]
I have the same problem, Then you know how to solve?

**Comment by iamthegD** [comment]
I faced this issue 404 but AFTER retrieving the project profile and the full analysis.

Somehow I can get the data from but I can't upload it to our sqube server.

**Comment by santhuhappy24** [comment]
I have the same issue,could any one please help to solve the above issue ?

Thank you in advance!

Regards,

Santhosh

**Comment by farhansumbul** [comment]
I had solved this issue long ago. Do not recollect how exactly :)
i think i had done re-started sonar server.
