### ISSUE TITLE
Support for SonarQube version 6.x

### ISSUE THREAD

**Issue by meddulla** [RadoBuransky/sonar-scoverage-plugin#38]
Hi,

Are there any plans to upgrade to the latest SonarQube (6.x)? If not, do you have any idea on the amount of work required and would you be open to a pull request on this?

Thanks

**Comment by s3ni0r** [comment]
i'm also in need of getting this to work with SonarQube version 6.0 ...

**Comment by RadoBuransky** [comment]
I can try to look at it within a week...Thanks.

**Comment by RadoBuransky** [comment]
There's quite a lot of breaking changes and deprecated stuff. I am not sure if I have enough time to fix it. Or I am just too lazy. Any volunteers?

**Comment by s3ni0r** [comment]
I really would like to, but i'm not familiar with the code base, it will take me even longer to understand and fix what has to be fixed.

**Comment by zafarella** [comment]
@RadoBuransky  push the branch with draft u have to repo, ppl can send PRs when time permits
+1 for support

**Comment by RadoBuransky** [comment]
I haven't gotten anywhere practically. Feel free to be the first one!

**Comment by MichaelZinsmaier** [comment]
hey guys,

I have sketched out an update to version 6.3 for our own environment. You can find it on the
dev branch of my fork. However there are some major issues (see Readme).

If somebody wants to continue from there feel free to do so. An alternative would be a rewrite dropping support for old scoverage files, revisting the whole relative / absolute branch issues ...

Also checkout https://github.com/Sagacify/sonar-scala I think it would be best to join efforts!
Especially since I have a feeling that some of the issues might be related to "hacky" language definition ...

Best regards Michael

**Comment by ryan-barker-zefr** [comment]
@MichaelZinsmaier I tried to build and upload your plugin but got the following error:
java.lang.IllegalStateException: Unable to read plugin manifest from jar : /opt/sonarqube/extensions/plugins/sonar-scoverage-plugin-5.1.3.jar
Any ideas?

**Comment by MichaelZinsmaier** [comment]
hm not much could be a version conflict? My current dev branch is intended for SonarQube 6.3
apart from that I just run a standard maven build and then drop the jar file in the extension folder
(test system is a linux system)

sry never saw this happening good luck

**Comment by Zephirin** [comment]
@MichaelZinsmaier So we ( @ryan-barker-zefr and I ) were able to get the plugin installed on SonarQube 6.3 but the scala language is not showing up as something I can put on a Quality Profile.  Any ideas where to start?

**Comment by JL-ChoqueChavez** [comment]
Hi guys, I would like to update the plugin code in order to add support for Sonarqube 6.x.
Anybody knows If there are a small manual or tutorials about how to to start it.

**Comment by MichaelZinsmaier** [comment]
@Zephirin  sorry no idea what the issue could be
@JL-ChoqueChavez  

I used mainly the following sources
[github](https://github.com/SonarSource/sonarqube)
[extension guide](https://docs.sonarqube.org/display/DEV/Extension+Guide)
[release notes](https://www.sonarqube.org/downloads/)

sadly the sonar guys do change a lot between versions and plugin documentation is sparse and slightly outdated. Looking at Git / the code is quite helpful from time to time.

good luck!

**Comment by JL-ChoqueChavez** [comment]
@Zephirin

Just in case I tried to use SonarQube 6.4 with the scoverage plugin.
If you use the scoverage plugin version 5.1.2, SonarQube detects and allow you to create the Scala profile, after to create the reports I executed the sonar-scanner to import the data but the next error appears (I'm trying to solve it):

Load plugins index
INFO: Load plugins index (done) | time=3ms
INFO: SonarQube server 6.4.0
INFO: Default locale: "en_US", source code encoding: "utf-8"
INFO: Process project properties
INFO: Load project repositories
INFO: Load project repositories (done) | time=16ms
INFO: Load quality profiles
INFO: ------------------------------------------------------------------------
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
INFO: Total time: 2.221s
INFO: Final Memory: 44M/284M
INFO: ------------------------------------------------------------------------
ERROR: Error during SonarQube Scanner execution
java.lang.IllegalStateException: Unable to load component class org.sonar.scanner.report.MetadataPublisher
	at org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer.getComponent(ComponentContainer.java:71)
	at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:621)
	at org.picocontainer.parameters.CollectionComponentParameter.getArrayInstance(CollectionComponentParameter.java:334)
	at org.picocontainer.parameters.CollectionComponentParameter.access$100(CollectionComponentParameter.java:49)

**Comment by dmytro-winged** [comment]
@JlccX how did you view statement coverage on SonarQube? As I understand, the plugin creates custom widget to view it. But all custom dashboards and widgets was dropped in [SonarQube v6.2](https://docs.sonarqube.org/display/SONAR/Release+6.2+Upgrade+Notes) ([SONAR-8354](https://jira.sonarsource.com/browse/SONAR-8354)).

Could you please provide some document or steps how to view statement coverage on SonarQube 6.4 with this plugin?

**Comment by jlccx-incontact** [comment]
Hi guys
Just in case I found a new plugin that you can use to import scoverage code coverage reports into sonarqube 6.x.

The plugins link is: https://github.com/Sagacify/sonar-scala/releases

**Comment by JlccX** [comment]
Hi guys
Just in case I found a new plugin that you can use to import scoverage (scala) code coverage reports into sonarqube 6.x.

The plugins link is: https://github.com/Sagacify/sonar-scala/releases
