### ISSUE TITLE
Could not open localhost:9000/sonar/ - ubuntu server 16.04.3

### ISSUE THREAD

**Issue by bsaitechnosales** [RadoBuransky/sonar-scoverage-plugin#45]
Hi
I  completed Sonarqube installation but web page is not accessible. I tried localhost i.e 192.168.0.111:9000/sonar/ on browser but it does not display any pages. Any feedback will be great help.
**Just incase if you wanted to check installation steps that i have followed then u can find from this** url------>https://drive.google.com/open?id=1MTagyGCHGQjIwYkjmx0GW4TlVC5X_4PT

**Checking log file shows CONNECTION REFUSED. I have attached the log file url below:-**

root@storage:/opt/sonar/logs# ls -ltr total 116 -rw-r--r-- 1 root root 42640 Jan 7 18:12 es.2018-01-07.log -rw-r--r-- 1 root root 5330 Jan 8 16:39 es.2018-01-08.log -rw-r--r-- 1 root root 21320 Jan 9 16:42 es.log -rw-r--r-- 1 root root 30319 Jan 9 16:42 sonar.log root@storage:/opt/sonar/logs#

https://drive.google.com/file/d/1dh60U8z5NZNBxU6U2hAoEZ9sjsSsdpFm/view?usp=sharing

https://drive.google.com/file/d/1iFc5ibZRtAe8TtggI0gb87oJxv_Wtqpo/view?usp=sharing

**NMAP Output**

root@storage:/opt/sonar/logs# nmap -v -p 9000 192.168.0.227

Starting Nmap 7.01 ( https://nmap.org ) at 2018-01-09 16:54 +0545 Initiating SYN Stealth Scan at 16:54 Scanning storage.bsaitechnosales.com (192.168.0.227) [1 port] Completed SYN Stealth Scan at 16:54, 0.22s elapsed (1 total ports) Nmap scan report for storage.example.com (192.168.0.227) Host is up (0.000041s latency). PORT STATE SERVICE 9000/tcp closed cslistener

Read data files from: /usr/bin/../share/nmap Nmap done: 1 IP address (1 host up) scanned in 0.32 seconds Raw packets sent: 1 (44B) | Rcvd: 2 (84B)

ES LOG OUTPUT 2018.01.09 09:21:25 ERROR es[][o.e.b.Bootstrap] Exception java.lang.RuntimeException: can not run elasticsearch as root at org.elasticsearch.bootstrap.Bootstrap.initializeNatives(Bootstrap.java:106) ~[ elasticsearch-5.6.3.jar:5.6.3] at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:195) ~[elasticsearc h-5.6.3.jar:5.6.3] at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:342) [elasticsearch- 5.6.3.jar:5.6.3]

**SONAR.LOG Output**

**root@storage:/opt/sonar/logs# more sonar.log**
Wrapper Started as Daemon
Launching a JVM...
Wrapper (Version 3.2.3) http://wrapper.tanukisoftware.org
Copyright 1999-2006 Tanuki Software, Inc. All Rights Reserved.

2018.01.07 15:23:08 INFO app[][o.s.a.AppFileSystem] Cleaning or creating temp directory
/opt/sonar/temp
2018.01.07 15:23:08 INFO app[][o.s.a.es.EsSettings] Elasticsearch listening on /127.0.0.
1:9001
2018.01.07 15:23:08 INFO app[][o.s.a.p.ProcessLauncherImpl] Launch process[[key='es', ip
cIndex=1, logFilenamePrefix=es]] from [/opt/sonar/elasticsearch]: /opt/sonar/elasticsearc
h/bin/elasticsearch -Epath.conf=/opt/sonar/temp/conf/es
2018.01.07 15:23:08 INFO app[][o.s.a.SchedulerImpl] Waiting for Elasticsearch to be up a
nd running
2018.01.07 15:23:08 INFO app[][o.e.p.PluginsService] no modules loaded
2018.01.07 15:23:08 INFO app[][o.e.p.PluginsService] loaded plugin [org.elasticsearch.tr
ansport.Netty4Plugin]
2018.01.07 15:23:08 WARN app[][o.s.a.p.AbstractProcessMonitor] Process exited with exit
value [es]: 1
2018.01.07 15:23:08 INFO app[][o.s.a.SchedulerImpl] Process [es] is stopped
2018.01.07 15:23:08 INFO app[][o.s.a.SchedulerImpl] SonarQube is stopped
Wrapper Stopped

**Comment by zishanbilal** [comment]
SonarSource has upgraded the Elasticsearch tool in its latest versions. As a result SonarQube cannot be run as a root. Unfortunately sonar documentation didn't covered this part. You need to perform few extra steps to run it properly.

- create a new group and user for sonar. (`/opt/sonarqube` is sonar installation directory in my case)
  `sudo groupadd sonar`
  `sudo useradd -c "Sonar System User" -d /opt/sonarqube -g sonar -s /bin/bash sonar`
- make new user owner of sonar installation directory and 
  `sudo chown -R sonar:sonar /opt/sonarqube`
- specify this new user in  `/opt/sonarqube/bin/linux-x86-64/sonar.sh`  by finding `RUN_AS_USER` entry, uncomment it and assign newly created user
  `RUN_AS_USER=sonar`

**Comment by zishanbilal** [comment]
This is not plugin specific issue, @RadoBuransky please close this issue.

**Comment by mrityunjeyan** [comment]
@zishanbilal  I have performed the steps you have mentioned and I am still getting the error `elasticsearch cannot be started as a root` in the `es.log`

**Comment by reach2jeyan** [comment]
@zishanbilal  I have performed the steps you have mentioned and I am still getting the error `elasticsearch cannot be started as a root` in the `es.log`

In the `sonar.sh` I have mentined `RUN_AS_USER` as this

`if [ "`$IDEXE -u -n`" = "$RUN_AS_USER" ]
        then
            # Already running as the configured user.  Avoid password prompts by not calling su.
            RUN_AS_USER="sonar"
        fi
`

Anything else I require to do ?

**Comment by kaliopane** [comment]
I'm reproducing the issue on Ubuntu 18.04.
I've followed the documentation guidelines, but Sonar fails to open port 9000. 
netstat does not produce any results for processes running on port 9000.
