### ISSUE TITLE
org.sonar.runner.impl.RunnerException: Unable to execute Sonar

### ISSUE THREAD

**Issue by ayushmishra2005** [RadoBuransky/sonar-scoverage-plugin#6]
I installed SonarQube Server 4.5 and SonarQube Runner 2.4. I added sonar-scoverage-plugin-1.1.0.jar in sonar plugins directory. In /opt/sonar-runner/sonar-runner.properties, I uncommented sonar.host.url=http://localhost:9000. 

I tried to use sonar -runner for this sample project https://github.com/RadoBuransky/sonar-scoverage-plugin/tree/master/samples/sbt/multi-module.

I executed two commands 

$ sbt clean scoverage:test

$ sonar-runner

I got this exception

INFO: ------------------------------------------------------------------------
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
Total time: 3.542s
Final Memory: 59M/343M
INFO: ------------------------------------------------------------------------
ERROR: Error during Sonar runner execution
org.sonar.runner.impl.RunnerException: Unable to execute Sonar
    at org.sonar.runner.impl.BatchLauncher$1.delegateExecution(BatchLauncher.java:91)
    at org.sonar.runner.impl.BatchLauncher$1.run(BatchLauncher.java:75)
    at java.security.AccessController.doPrivileged(Native Method)
    at org.sonar.runner.impl.BatchLauncher.doExecute(BatchLauncher.java:69)
    at org.sonar.runner.impl.BatchLauncher.execute(BatchLauncher.java:50)
    at org.sonar.runner.api.EmbeddedRunner.doExecute(EmbeddedRunner.java:102)
    at org.sonar.runner.api.Runner.execute(Runner.java:100)
    at org.sonar.runner.Main.executeTask(Main.java:70)
    at org.sonar.runner.Main.execute(Main.java:59)
    at org.sonar.runner.Main.main(Main.java:53)
Caused by: java.lang.IllegalStateException: Fail to execute request [code=500, url=http://localhost:9000/batch/project?key=com.buransky:multi-module&amp;preview=false]
    at org.sonar.batch.bootstrap.ServerClient.handleHttpException(ServerClient.java:121)
    at org.sonar.batch.bootstrap.ServerClient.request(ServerClient.java:89)
    at org.sonar.batch.bootstrap.ServerClient.request(ServerClient.java:81)
    at org.sonar.batch.bootstrap.ServerClient.request(ServerClient.java:77)
    at org.sonar.batch.referential.DefaultProjectReferentialsLoader.load(DefaultProjectReferentialsLoader.java:55)
    at org.sonar.batch.referential.ProjectReferentialsProvider.provide(ProjectReferentialsProvider.java:40)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.picocontainer.injectors.MethodInjector.invokeMethod(MethodInjector.java:129)
    at org.picocontainer.injectors.MethodInjector.access$000(MethodInjector.java:39)
    at org.picocontainer.injectors.MethodInjector$2.run(MethodInjector.java:113)
    at org.picocontainer.injectors.AbstractInjector$ThreadLocalCyclicDependencyGuard.observe(AbstractInjector.java:270)
    at org.picocontainer.injectors.MethodInjector.decorateComponentInstance(MethodInjector.java:120)
    at org.picocontainer.injectors.CompositeInjector.decorateComponentInstance(CompositeInjector.java:58)
    at org.picocontainer.injectors.Reinjector.reinject(Reinjector.java:142)
    at org.picocontainer.injectors.ProviderAdapter.getComponentInstance(ProviderAdapter.java:96)
    at org.picocontainer.DefaultPicoContainer.getInstance(DefaultPicoContainer.java:698)
    at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:646)
    at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:631)
    at org.picocontainer.parameters.BasicComponentParameter$1.resolveInstance(BasicComponentParameter.java:118)
    at org.picocontainer.parameters.ComponentParameter$1.resolveInstance(ComponentParameter.java:136)
    at org.picocontainer.injectors.SingleMemberInjector.getParameter(SingleMemberInjector.java:78)
    at org.picocontainer.injectors.ConstructorInjector$CtorAndAdapters.getParameterArguments(ConstructorInjector.java:309)
    at org.picocontainer.injectors.ConstructorInjector$1.run(ConstructorInjector.java:335)
    at org.picocontainer.injectors.AbstractInjector$ThreadLocalCyclicDependencyGuard.observe(AbstractInjector.java:270)
    at org.picocontainer.injectors.ConstructorInjector.getComponentInstance(ConstructorInjector.java:364)
    at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.getComponentInstance(AbstractInjectionFactory.java:56)
    at org.picocontainer.behaviors.AbstractBehavior.getComponentInstance(AbstractBehavior.java:64)
    at org.picocontainer.behaviors.Stored.getComponentInstance(Stored.java:91)
    at org.picocontainer.DefaultPicoContainer.getInstance(DefaultPicoContainer.java:698)
    at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:646)
    at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:677)
    at org.sonar.api.platform.ComponentContainer.getComponentByType(ComponentContainer.java:198)
    at org.sonar.batch.scan.ProjectScanContainer.doBeforeStart(ProjectScanContainer.java:102)
    at org.sonar.api.platform.ComponentContainer.startComponents(ComponentContainer.java:90)
    at org.sonar.api.platform.ComponentContainer.execute(ComponentContainer.java:77)
    at org.sonar.batch.scan.ScanTask.scan(ScanTask.java:64)
    at org.sonar.batch.scan.ScanTask.execute(ScanTask.java:51)
    at org.sonar.batch.bootstrap.TaskContainer.doAfterStart(TaskContainer.java:125)
    at org.sonar.api.platform.ComponentContainer.startComponents(ComponentContainer.java:92)
    at org.sonar.api.platform.ComponentContainer.execute(ComponentContainer.java:77)
    at org.sonar.batch.bootstrap.BootstrapContainer.executeTask(BootstrapContainer.java:173)
    at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:95)
    at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:67)
    at org.sonar.runner.batch.IsolatedLauncher.execute(IsolatedLauncher.java:48)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.sonar.runner.impl.BatchLauncher$1.delegateExecution(BatchLauncher.java:87)
    ... 9 more
Caused by: org.sonar.api.utils.HttpDownloader$HttpException: Fail to download [http://localhost:9000/batch/project?key=com.buransky:multi-module&amp;preview=false]. Response code: 500
    at org.sonar.api.utils.HttpDownloader$BaseHttpDownloader$HttpInputSupplier.getInput(HttpDownloader.java:281)
    at org.sonar.api.utils.HttpDownloader$BaseHttpDownloader$HttpInputSupplier.getInput(HttpDownloader.java:235)
    at org.sonar.batch.bootstrap.ServerClient.request(ServerClient.java:87)
    ... 59 more

Could you please help me to resolve this? Thanks in advance.

**Comment by vishwnahak** [comment]
Hi 

Anyone used sonar-runner in Android studio  , when I run command "gradle sonarRunner"  through terminal it give error as below :
"Can not invoke method public java.lang.Class org.sonar.plugins.surefire.SurefireSensor.dependsUponCoverageSensors()"


My Build.gradle file  as below:
apply plugin: 'sonar-runner'

 sonarRunner {
        sonarProperties {
// can be also set on command line like -Dsonar.analysis.mode=incremental
            property "sonar.host.url", "http://myserver.com"
            property 'sonar.sourceEncoding', 'UTF-8'
            property 'sonar.language', 'java'
            property 'sonar.projectKey', 'com.projectKey'
            //need to replace with your project package name
            property 'sonar.projectName', 'projectName' // need to replace with your project name
            property 'sonar.projectVersion', '1.0'
           property 'sonar.sources', 'src/main/java'
        }
    }


 If any one have any solution then please help me I am stuck here.

My Android studio  version- 1.3.2
SonarQube Runner 2.3
SonarQube Server 5.3

**Comment by govindpandav** [comment]
// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.1.2'
        classpath 'com.dicedmelon.gradle:jacoco-android:0.1.1'
    }
}
plugins {
    id "org.sonarqube" version "1.2"
}

allprojects {
    repositories {
        jcenter()
    }

    sonarqube {

        def flavor = "develop" // flavor we want to have tested. Should be static


        properties {

            def libraries =/* project.android.sdkDirectory.getPath() + */"C:/Users/pandav.govind/Desktop/adt-bundle/adt-bundle-windows-x86_64-20140321/sdk/platforms/android-23/android.jar," +
                    "C:/Users/pandav.govind/Desktop/HDFC-CVU-ISG-PWC/app/build/intermediates/exploded-aar/**/classes.jar"

            property "sonar.host.url", "http://localhost:9010"
            property "sonar.projectKey", "CVU" // some shortcut name
            property "sonar.projectName", "HDFC-CVU-ISG-PWC"
            property "sonar.jacoco.reportPath","C:/Users/pandav.govind/Desktop/HDFC-CVU-ISG-PWC/app/build/outputs/code-coverage/connected/flavors/DEVELOP/coverage.ec"
            property "sonar.language", "java"
            property "sonar.sources", "src/main"
            property "sonar.projectVersion","1.0"
            property "sonar.binaries", "C:/Users/pandav.govind/Desktop/HDFC-CVU-ISG-PWC/app/build/intermediates/classes/${flavor}/debug"
            property "sonar.libraries", libraries

            property "sonar.java.binaries", "C:/Users/pandav.govind/Desktop/HDFC-CVU-ISG-PWC/app/build/intermediates/classes/${flavor}/debug"
            property "sonar.java.libraries", libraries

            property "sonar.tests", "src/test/java" // where the tests are located
            property "sonar.java.test.binaries", "C:/Users/pandav.govind/Desktop/HDFC-CVU-ISG-PWC/app/build/intermediates/classes/${flavor}/debug"
            property "sonar.java.test.libraries", libraries

            // property "sonar.tests", "src/androidTest/"
            property "sonar.scm.disabled", "true"



        }
    }
}
task clean(type: Delete) {
    delete rootProject.buildDir
}

import org.gradle.internal.os.OperatingSystem;

task sonarComplete1(type: Exec) {
    def Flavor = "Develop"
    def command = "gradlew"
    if (OperatingSystem.current().isWindows()) {
        command = command + ".bat"
    }
    commandLine command, "clean", "connectedAndroidTest", "create${Flavor}DebugCoverageReport", "test","jacocoTestReport", "sonarqube"
}

--------------------------
move to project root directory copy path to cmd and run command
gradlew sonarComplete1
it works
...
but when it runs your android device or genymotion or Virtual Device open
